name: globens_flutter_client
description: Globens Flutter Client Application (iOS + Android)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # region default
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  tuple: ^1.0.3
  # endregion
  # region gRPC
  async: ^2.2.0
  grpc: ^2.8.0
  protobuf: ^1.1.0
  protoc_plugin: ^19.2.0+1
  # endregion
  # region kakao auth
  kakao_flutter_sdk: ^0.5.2
  dio: ^3.0.10 #latest version
  json_annotation: ^3.0.0
  platform: ^2.2.1
  package_info: ^0.4.1
  # endregion
  # region google, facebook auth
  google_sign_in: ^4.5.6
  # endregion
  # region bottom_sheet
  modal_bottom_sheet: ^0.2.0+1
  # endregion
  # region toast
  fluttertoast: ^7.0.2
  # endregion
  # region shared_preferences
  shared_preferences: ^0.5.8
  # endregion
  #region http
  http: ^0.12.0+4
  #endregion
  #region json
  json_conditional: ^1.0.2
  #endregion

  #region camera
  path: ^1.7.0
  path_provider: ^1.6.14
  camera: ^0.5.8+5
  #endregion
  #region
  image_picker: ^0.6.7+7
  #endregion
  #region
  connectivity: ^2.0.1
  #endregion
  webview_flutter: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  # region kakao auth
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  # endregion
  # region in app purchases
  pedantic: ^1.8.0
  # endregion

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    - assets/facebook.png
    - assets/google.png
    - assets/kakaotalk.png
    - assets/business_page_placeholder.png
    - assets/education.png
    - assets/consultation.png
    - assets/job.png
    - assets/others.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
